export const languages = [
  { name: "ActionScript", color: "#882B0F" },
  { name: "Agda", color: "#315665" },
  { name: "Alloy", color: "#64C800" },
  { name: "Ant Build System", color: "#E6E6E6" },
  { name: "ANTLR", color: "#9DC3FF" },
  { name: "AppleScript", color: "#101F1F" },
  { name: "Arc", color: "#aa2afe" },
  { name: "Arduino", color: "#bd79d1" },
  { name: "AspectJ", color: "#a957b0" },
  { name: "Assembly", color: "#6E4C13" },
  { name: "Astro", color: "#ff5a03" },
  { name: "ATS", color: "#1ac620" },
  { name: "Ballerina", color: "#FF5000" },
  { name: "Batchfile", color: "#C1F12E" },
  { name: "BibTeX", color: "#778899" },
  { name: "Blade", color: "#f7523f" },
  { name: "Boo", color: "#d4bec1" },
  { name: "C", color: "#555555" },
  { name: "C#", color: "#178600" },
  { name: "C++", color: "#f34b7d" },
  { name: "Cabal Config", color: "#483465" },
  { name: "Cap'n Proto", color: "#cdd0e3" },
  { name: "CartoCSS", color: "#D1F9FF" },
  { name: "Ceylon", color: "#dfa535" },
  { name: "Chapel", color: "#8dc63f" },
  { name: "ChucK", color: "#3f8000" },
  { name: "Cirru", color: "#ccccff" },
  { name: "Clarion", color: "#db901e" },
  { name: "Clean", color: "#3F85AF" },
  { name: "Click", color: "#E4E6F3" },
  { name: "CLIPS", color: "#00A300" },
  { name: "Clojure", color: "#db5855" },
  { name: "Closure Templates", color: "#0d948f" },
  { name: "Cloud Firestore Security Rules", color: "#FFCA28" },
  { name: "CMake", color: "#064f8c" },
  { name: "COBOL", color: "#464366" },
  { name: "CodeQL", color: "#140f46" },
  { name: "ColdFusion", color: "#ed2cd6" },
  { name: "Common Lisp", color: "#3fb68b" },
  { name: "Component Pascal", color: "#B0CE4E" },
  { name: "Cool", color: "#6B9DC2" },
  { name: "Coq", color: "#d0b0e4" },
  { name: "Crystal", color: "#776791" },
  { name: "CSP", color: "#E4E6F3" },
  { name: "CSS", color: "#563d7c" },
  { name: "D", color: "#ba595e" },
  { name: "Dafny", color: "#FFEC25" },
  { name: "Dart", color: "#00B4AB" },
  { name: "Delphi", color: "#c0ce4e" },
  { name: "Diff", color: "#88dddd" },
  { name: "DIGITAL Command Language", color: "#da0b35" },
  { name: "DM", color: "#447265" },
  { name: "Dockerfile", color: "#384d54" },
  { name: "Dogescript", color: "#cca760" },
  { name: "DTrace", color: "#fffacd" },
  { name: "Dylan", color: "#6c616e" },
  { name: "E", color: "#ccce35" },
  { name: "Eagle", color: "#814C05" },
  { name: "Easybuild", color: "#add8e6" },
  { name: "Ecere Projects", color: "#913960" },
  { name: "ECL", color: "#8a1267" },
  { name: "ECLiPSe", color: "#b0ce4e" },
  { name: "EGL", color: "#00cc99" },
  { name: "Eiffel", color: "#946d57" },
  { name: "Elixir", color: "#6e4a7e" },
  { name: "Emacs Lisp", color: "#c065db" },
  { name: "EmberScript", color: "#FFF4F3" },
  { name: "Erlang", color: "#B83998" },
  { name: "F#", color: "#b845fc" },
  { name: "Factor", color: "#636746" },
  { name: "Fancy", color: "#7b9db4" },
  { name: "Fantom", color: "#14253c" },
  { name: "Filebench WML", color: "#1E14B6" },
  { name: "Filterscript", color: "#c4ecee" },
  { name: "Fish", color: "#4aae47" },
  { name: "FLUX", color: "#88ccff" },
  { name: "Formatted", color: "#ff79c6" },
  { name: "Forth", color: "#341708" },
  { name: "Fortran", color: "#4d41b1" },
  { name: "FreeMarker", color: "#0050b2" },
  { name: "Frege", color: "#00cafe" },
  { name: "Game Maker Language", color: "#8fb200" },
  { name: "GAML", color: "#FFC766" },
  { name: "GAP", color: "#0000cc" },
  { name: "GDScript", color: "#355570" },
  { name: "Genie", color: "#fb855d" },
  { name: "Genshi", color: "#9517aa" },
  { name: "Gentoo Ebuild", color: "#d9df01" },
  { name: "Gentoo Eclass", color: "#d9df01" },
  { name: "Gerber Image", color: "#D3D3D3" },
  { name: "Gettext Catalog", color: "#000000" },
  { name: "Gherkin", color: "#5B2063" },
  { name: "GLSL", color: "#5686A5" },
  { name: "Glyph", color: "#e4cc98" },
  { name: "Glyph Bitmap Distribution Format", color: "#e4cc98" },
  { name: "GNUplot", color: "#f0a9f0" },
  { name: "GnuTLS Config", color: "#5e5554" },
  { name: "Go", color: "#00ADD8" },
  { name: "Golo", color: "#88562A" },
  { name: "Gosu", color: "#82937f" },
  { name: "Grace", color: "#615f8c" },
  { name: "Gradle", color: "#02303A" },
  { name: "Grammatical Framework", color: "#79aa7a" },
  { name: "GraphQL", color: "#e10098" },
  { name: "Graphviz (DOT)", color: "#fcbf49" },
  { name: "Groovy", color: "#e69f56" },
  { name: "Groovy Server Pages", color: "#4298b8" },
  { name: "Hack", color: "#878787" },
  { name: "Harbour", color: "#0e60e3" },
  { name: "Haskell", color: "#5e5086" },
  { name: "Haxe", color: "#df7900" },
  { name: "HCL", color: "#284b63" },
  { name: "HiveQL", color: "#dce200" },
  { name: "HLSL", color: "#aace60" },
  { name: "HolyC", color: "#ffefaf" },
  { name: "HTML", color: "#e34c26" },
  { name: "Hy", color: "#7790B2" },
  { name: "HyPhy", color: "#7790B2" },
  { name: "IDL", color: "#a3522f" },
  { name: "Idris", color: "#b30000" },
  { name: "Ignore List", color: "#000000" },
  { name: "IGOR Pro", color: "#0e60e3" },
  { name: "ImageJ Macro", color: "#99AAFF" },
  { name: "Inform 7", color: "#F69E1D" },
  { name: "Inno Setup", color: "#264b99" },
  { name: "Io", color: "#a9188d" },
  { name: "Ioke", color: "#078193" },
  { name: "Isabelle", color: "#FEFE00" },
  { name: "J", color: "#9EEDFF" },
  { name: "Jasmin", color: "#F8CE5D" },
  { name: "Java", color: "#b07219" },
  { name: "JavaScript", color: "#f1e05a" },
  { name: "JFlex", color: "#DBCA00" },
  { name: "Jison", color: "#56b3fb" },
  { name: "Jolie", color: "#843179" },
  { name: "JSON", color: "#292929" },
  { name: "Julia", color: "#a270ba" },
  { name: "Jupyter Notebook", color: "#DA5B0B" },
  { name: "Just", color: "#384d54" },
  { name: "Kotlin", color: "#A97BFF" },
  { name: "KRL", color: "#28431f" },
  { name: "LabVIEW", color: "#FDE3E3" },
  { name: "Lasso", color: "#999999" },
  { name: "LaTeX", color: "#3D6117" },
  { name: "Lean", color: "#CC302B" },
  { name: "Less", color: "#1d365d" },
  { name: "Lex", color: "#DBCA00" },
  { name: "LFE", color: "#4C3023" },
  { name: "LilyPond", color: "#9F7A3A" },
  { name: "Limbo", color: "#669999" },
  { name: "Liquid", color: "#999999" },
  { name: "Literate Agda", color: "#315665" },
  { name: "Literate CoffeeScript", color: "#244776" },
  { name: "Literate Haskell", color: "#5e5086" },
  { name: "LiveScript", color: "#499886" },
  { name: "LLVM", color: "#185619" },
  { name: "Logos", color: "#8a1267" },
  { name: "Logtalk", color: "#2954a3" },
  { name: "LOLCODE", color: "#cc9900" },
  { name: "LookML", color: "#652B81" },
  { name: "LoomScript", color: "#42c0f3" },
  { name: "LSL", color: "#3d9970" },
  { name: "Lua", color: "#000080" },
  { name: "M", color: "#f0a040" },
  { name: "M4", color: "#eaeaea" },
  { name: "M4Sugar", color: "#eaeaea" },
  { name: "MAD", color: "#b0ce4e" },
  { name: "Magic", color: "#fafad2" },
  { name: "Makefile", color: "#427819" },
  { name: "Mako", color: "#7e858d" },
  { name: "Markdown", color: "#083fa1" },
  { name: "Marko", color: "#42f1f4" },
  { name: "Mask", color: "#f97732" },
  { name: "Mathematica", color: "#dd1100" },
  { name: "Matlab", color: "#bb92ac" },
  { name: "Max", color: "#ce279c" },
  { name: "MAXScript", color: "#00a6a6" },
  { name: "Mercury", color: "#ff2b2b" },
  { name: "Meson", color: "#007800" },
  { name: "Metal", color: "#8f14e9" },
  { name: "MiniD", color: "#FDE3E3" },
  { name: "Mirah", color: "#c7a938" },
  { name: "Modelica", color: "#de1d31" },
  { name: "Modula-2", color: "#223388" },
  { name: "Module Management System", color: "#7ac5cd" },
  { name: "Monkey", color: "#ff6600" },
  { name: "Moocode", color: "#3b9e89" },
  { name: "MoonScript", color: "#ffaf5f" },
  { name: "MQL4", color: "#62A8D6" },
  { name: "MQL5", color: "#4A76B8" },
  { name: "MTML", color: "#b7e1f4" },
  { name: "MUF", color: "#c53151" },
  { name: "Mupad", color: "#e0b0ff" },
  { name: "Myghty", color: "#c0c0c0" },
  { name: "NCL", color: "#28431f" },
  { name: "Nearley", color: "#990000" },
  { name: "Nemerle", color: "#3d3c6e" },
  { name: "nesC", color: "#94B0C7" },
  { name: "NetLinx", color: "#0aa0ff" },
  { name: "NetLinx+ERB", color: "#747faa" },
  { name: "NetLogo", color: "#ff6375" },
  { name: "NewLisp", color: "#87AED7" },
  { name: "Nextflow", color: "#3ac486" },
  { name: "Nginx", color: "#009639" },
  { name: "Nim", color: "#37775b" },
  { name: "Nit", color: "#009917" },
  { name: "Nix", color: "#7e7eff" },
  { name: "NL", color: "#ff0000" },
  { name: "NPM Config", color: "#cbcb41" },
  { name: "NSIS", color: "#000080" },
  { name: "Nu", color: "#c9df40" },
  { name: "NumPy", color: "#9C8AF9" },
  { name: "ObjDump", color: "#f84e1d" },
  { name: "Objective-C", color: "#438eff" },
  { name: "Objective-C++", color: "#6866fb" },
  { name: "Objective-J", color: "#ff0c5a" },
  { name: "Odin", color: "#60AFFE" },
  { name: "Omgrofl", color: "#cabbff" },
  { name: "ooc", color: "#b0b77e" },
  { name: "Opa", color: "#a6e491" },
  { name: "Opal", color: "#f7ede0" },
  { name: "OpenCL", color: "#f3dfc7" },
  { name: "OpenEdge ABL", color: "#5ce600" },
  { name: "OpenSCAD", color: "#e5cd36" },
  { name: "OpenGL Shading Language", color: "#6e4a7e" },
  { name: "OpenQASM", color: "#d6adfa" },
  { name: "OpenRC runscript", color: "#66cdaa" },
  { name: "Org", color: "#6e4a7e" },
  { name: "Ox", color: "#f0aaaa" },
  { name: "Oxygene", color: "#cdd0e3" },
  { name: "Oz", color: "#fab738" },
  { name: "P4", color: "#7055b5" },
  { name: "Pan", color: "#cc0000" },
  { name: "Papyrus", color: "#6600cc" },
  { name: "Parrot", color: "#f3ca0a" },
  { name: "Parrot Assembly", color: "#f3ca0a" },
  { name: "Parrot Internal Representation", color: "#f3ca0a" },
  { name: "Pascal", color: "#E3F171" },
  { name: "Pawn", color: "#dbb284" },
  { name: "Pep8", color: "#C76F5B" },
  { name: "Perl", color: "#0298c3" },
  { name: "PHP", color: "#4F5D95" },
  { name: "Pic", color: "#6a6aec" },
  { name: "PigLatin", color: "#fcd7de" },
  { name: "Pike", color: "#005390" },
  { name: "Pill", color: "#d9b12e" },
  { name: "Pioneer", color: "#54acff" },
  { name: "Piranha", color: "#c701c6" },
  { name: "PogoScript", color: "#d80074" },
  { name: "Pony", color: "#0580B0" },
  { name: "PostScript", color: "#da291c" },
  { name: "PowerBuilder", color: "#8f0f8d" },
  { name: "PowerShell", color: "#012456" },
  { name: "Prisma", color: "#0c344b" },
  { name: "Processing", color: "#0096D8" },
  { name: "Prolog", color: "#74283c" },
  { name: "Propeller Spin", color: "#7fa2a7" },
  { name: "Pug", color: "#a86454" },
  { name: "Puppet", color: "#302B6D" },
  { name: "Pure Data", color: "#91de79" },
  { name: "PureScript", color: "#1D222D" },
  { name: "Python", color: "#3572A5" },
  { name: "Q#", color: "#fed659" },
  { name: "QMake", color: "#808000" },
  { name: "QML", color: "#44a51c" },
  { name: "Qt Script", color: "#00b0ef" },
  { name: "Quake", color: "#882233" },
  { name: "R", color: "#198CE7" },
  { name: "Racket", color: "#3c5caa" },
  { name: "Ragel", color: "#9d5200" },
  { name: "RAML", color: "#77d9fb" },
  { name: "Rascal", color: "#fffaa0" },
  { name: "Razor", color: "#512be4" },
  { name: "ReScript", color: "#ed5050" },
  { name: "Reason", color: "#ed5050" },
  { name: "Rebol", color: "#358a5b" },
  { name: "Red", color: "#f50000" },
  { name: "Redcode", color: "#ff0000" },
  { name: "Ren'Py", color: "#ff7f7f" },
  { name: "RenderScript", color: "#ff2a00" },
  { name: "Roff", color: "#ecdebe" },
  { name: "Rouge", color: "#cc0088" },
  { name: "Ruby", color: "#701516" },
  { name: "Rust", color: "#dea584" },
  { name: "Sage", color: "#9dc3e6" },
  { name: "SaltStack", color: "#646464" },
  { name: "SAS", color: "#B34936" },
  { name: "Scala", color: "#c22d40" },
  { name: "Scheme", color: "#1e4aec" },
  { name: "Scilab", color: "#1d659e" },
  { name: "SCSS", color: "#c6538c" },
  { name: "sed", color: "#64b970" },
  { name: "Self", color: "#0579aa" },
  { name: "ShaderLab", color: "#222c37" },
  { name: "Shell", color: "#89e051" },
  { name: "ShellSession", color: "#89e051" },
  { name: "SilverStripe", color: "# silver" },
  { name: "Singularity", color: "#c2b0a3" },
  { name: "Slash", color: "#007eff" },
  { name: "Slice", color: "#003fa2" },
  { name: "Slim", color: "#ff8f77" },
  { name: "Smali", color: "#A7C25C" },
  { name: "Smalltalk", color: "#596706" },
  { name: "Smarty", color: "#f0c040" },
  { name: "SML", color: "#dc566d" },
  { name: "Solidity", color: "#AA6746" },
  { name: "SQF", color: "#3F3F3F" },
  { name: "SQL", color: "#e38c00" },
  { name: "Squirrel", color: "#800000" },
  { name: "SRecode Template", color: "#348a34" },
  { name: "Stan", color: "#b2011d" },
  { name: "Standard ML", color: "#dc566d" },
  { name: "Starlark", color: "#76d275" },
  { name: "Stata", color: "#1a5f91" },
  { name: "STON", color: "#b9d9ff" },
  { name: "Stylus", color: "#ff6347" },
  { name: "SubRip Text", color: "#9e0101" },
  { name: "SugarSS", color: "#F96568" },
  { name: "SuperCollider", color: "#46390b" },
  { name: "Svelte", color: "#ff3e00" },
  { name: "Swift", color: "#ffac45" },
  { name: "SystemVerilog", color: "#DAE1C2" },
  { name: "Tcl", color: "#e4cc98" },
  { name: "Tcsh", color: "#244776" },
  { name: "TeX", color: "#3D6117" },
  { name: "Thrift", color: "#D12127" },
  { name: "Turing", color: "#45f715" },
  { name: "Twig", color: "#c1d026" },
  { name: "TypeScript", color: "#3178c6" },
  { name: "Unified Parallel C", color: "#4e3617" },
  { name: "Unity3D Asset", color: "#222c37" },
  { name: "Unix Assembly", color: "#6E4C13" },
  { name: "Uno", color: "#9933cc" },
  { name: "UnrealScript", color: "#a54c4d" },
  { name: "UrWeb", color: "#ccc" },
  { name: "V", color: "#4f87c4" },
  { name: "Vala", color: "#fbe5cd" },
  { name: "Vim script", color: "#199c4b" },
  { name: "Visual Basic", color: "#945db7" },
  { name: "Volt", color: "#1F1F1F" },
  { name: "Vue", color: "#2c3e50" },
  { name: "WebAssembly", color: "#04133b" },
  { name: "WebIDL", color: "#0eaa00" },
  { name: "WikiMarkup", color: "#f8f8f8" },
  { name: "Wollok", color: "#a23738" },
  { name: "World of Warcraft Addon Data", color: "#f2c200" },
  { name: "X10", color: "#4B6BEF" },
  { name: "xBase", color: "#403a40" },
  { name: "Xojo", color: "#22228f" },
  { name: "Xonsh", color: "#285EEF" },
  { name: "XProc", color: "#E4E6F3" },
  { name: "XQuery", color: "#5232e7" },
  { name: "XS", color: "#e52b50" },
  { name: "XSLT", color: "#EB8CEB" },
  { name: "Xtend", color: "#a4bdfc" },
  { name: "Yacc", color: "#4B6C4B" },
  { name: "YAML", color: "#cb171e" },
  { name: "YANG", color: "#0c715c" },
  { name: "Zephir", color: "#118f9e" },
  { name: "Zig", color: "#ec915c" },
  { name: "ZIL", color: "#dc75e5" },
  { name: "Zimpl", color: "#dbe9ff" },
];